/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Notification {
  'id' : bigint,
  'ownerId' : Principal,
  'isRead' : boolean,
  'orderId' : bigint,
  'message' : string,
  'timestamp' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'paymentStatus' : string,
  'shopId' : bigint,
  'productId' : bigint,
  'paymentProof' : [] | [ExternalBlob],
  'quantity' : bigint,
  'paymentNote' : string,
  'commissionAmount' : bigint,
  'customerId' : Principal,
  'totalPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'shopId' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Shop {
  'id' : bigint,
  'latitude' : number,
  'tiktok' : string,
  'owner' : Principal,
  'instagram' : string,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'whatsapp' : string,
  'description' : string,
  'paymentNumbers' : string,
  'facebook' : string,
  'longitude' : number,
  'address' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'profilePicture' : [] | [ExternalBlob],
  'preferredTheme' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, ExternalBlob, bigint, bigint],
    bigint
  >,
  'createShop' : ActorMethod<
    [string, string, string, number, number, string, string, string, string],
    bigint
  >,
  'deleteShop' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getShop' : ActorMethod<[bigint], [] | [Shop]>,
  'getShopOrders' : ActorMethod<[bigint], Array<Order>>,
  'getShopProducts' : ActorMethod<[bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[bigint, bigint], bigint>,
  'registerProfile' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, ExternalBlob, bigint],
    undefined
  >,
  'updateProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'updateShop' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateShopLogo' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'updateShopPaymentNumbers' : ActorMethod<[bigint, string], undefined>,
  'updatePaymentNote' : ActorMethod<[bigint, string], undefined>,
  'uploadPaymentProof' : ActorMethod<[bigint, ExternalBlob, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];